import "@/public/styles/login.scss";
import { Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Verification",
  description: "Generated by webdads2u",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
